### ISSUE TITLE
seccomp.h not found

### ISSUE THREAD

**Issue by MichaelStollBayreuth** [nomeata/loogle#10]
I'm trying to install loogle locally on my machine (running SuSE Tumbleweed). When I try `lake exe loogle --help` (after the `lake exe cache get` step), I get the error message
```bash
mstoll@xxx:~/lean4/loogle> lake exe loogle --help
info: [0/68] Compiling Seccomp c shim (.o)
error: > cc -c -o ./.lake/build/loogle_seccomp.o ./loogle_seccomp.c -I /home/mstoll/.elan/toolchains/leanprover--lean4---v4.5.0-rc1/include -fPIC
error: stderr:
./loogle_seccomp.c:3:10: fatal error: seccomp.h: No such file or directory
    3 | #include <seccomp.h>
      |          ^~~~~~~~~~~
compilation terminated.
error: external command `cc` exited with code 1
```
There is a file `/usr/inlcude/linux/seccomp.h`, but no `/usr/include/seccomp.h`. Commenting out line 3 of `loogle_seccomp.c` (which does the `#include` that the compiler is complaining about), I get loads of error messages pointing to missing declarations. Installing the `libseccomp-devel` package seems to provide a suitable `seccomp.h` file, but in the directory `/usr/include/libseccomp/`, which does not seem to be in the path searched for header files. Adding `/libseccomp` in suitable places helps.

Maybe at some point the presence (or whereabouts) of relevant header files can be checked (before they are needed to compile something), and a helpful message be printed if they are not there or not where they are expected?

**Comment by nomeata** [comment]
Thanks for trying out loogle!

The seccomp support is only really relevant when running loogle as a public service, else it’s just a distraction. I should make seccomp optional somehow in a way that users by default do not have to deal with it. Not sure how to implement such conditional compilation, though.

**Comment by femtomc** [comment]
Just a note that this also breaks the build process on MacOS (as far as I can tell).

However, I'm using `cc = clang` -- and I haven't tried explicitly using `gcc`. I can try a few more things and report back.

**Comment by nomeata** [comment]
For now, just comment out the two lines mentioning seccomp in the main file, and maybe in the lakefile.lean, and it should work.

**Comment by femtomc** [comment]
@nomeata Sorry, can you be a bit more specific -- I'm a bit new to the organizational aspects of Lean projects. (I can see `lakefile.lean` -- but the main file?)

**Comment by nomeata** [comment]
In `Loogle.lean`, there are these two lines
```
import Seccomp
```
and
```
    Seccomp.enable
```
