### ISSUE TITLE
`uncaught exception: unknown package 'ImportGraph'` when Mathlib is not built

### ISSUE THREAD

**Issue by dranov** [nomeata/loogle#12]
If I run `lake exe loogle '(List.replicate (_ + _) _ = _)'` (the example command in the `README`) without running `lake build LoogleMathlibCache` beforehand, I get the following very uninformative error:

```
uncaught exception: unknown package 'ImportGraph'
```

Running `lake build LoogleMathlibCache` fixes the issue.

**Comment by nomeata** [comment]
Thanks!

Essentially, if you don’t pass `--module`, it tries to load `Mathlib` and its dependencies. Probably `lake build LoogleMathlibCache`, besides building the cache, built `Mathlib`.

So I expect `lake build Mathlib` would have helped just the same (but building the cache is of course also good, makes the queries faster).

Did you run `lake exe cache get` before?

**Comment by nomeata** [comment]
I think this used to work, `ImportGraph` is a new dependency, so there is something to debug here… ah, yes, it’s a problem with mathlib:
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Imports.20are.20out.20of.20date.20even.20after.20getting.20cache.2E/near/412772807

So once that’s resolved it should work here as well again.

**Comment by nomeata** [comment]
Should be fixed now that I updated mathlib. Thanks for reporting!
